- grid/src/main/java/step/grid/agent/Agent.java
- grid/src/main/java/step/grid/agent/conf/AgentConf.java
I have added a setting into AgentConf and Agent in order to be able to setup only the agent host when starting an Agent.
This will be useful for the Cloud application and give more flexibility.
> Added agent host configuration ability

- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/CancellableSleep.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/RetryIfFailsHandler.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/SequenceHandler.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/SleepHandler.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/ThreadGroupHandler.java
Fixes Threadgroup rampup timing as well.
> SED-370 SED-471 Improve interruptions of executions

- step-functions-plugins/step-functions-plugins-java/step-functions-plugins-java-def/src/main/java/step/plugins/java/GeneralScriptFunctionType.java
This is already live and working at ADC as a customer-specific patch...
> SED-1606 Support Error Handlers for generic scripts

- step-repositories/step-repositories-artifact/src/main/java/step/repositories/artifact/ArtifactRepository.java
- step-repositories/step-repositories-artifact/src/main/java/step/repositories/artifact/StepJarParser.java
Adding parameters for managing libraries
> Sed 1563 open source http repository

- step-libs-maven-client/src/main/java/step/repositories/artifact/MavenArtifactClient.java
Fixing bug when trying to parse a SNAPSHOT file
> Sed 1846 add system property

- build_parameters.json
- step-parent/pom.xml
Optimize build times by skipping javadoc generation when not required.
> SED-2026 Optimize build times

- step-plans/step-plans-core/src/main/java/step/core/artefacts/handlers/ArtefactHandler.java
> SED-1042 stack-overflow-error-error-not-catched-with-recursive-plans

- step-plans/step-plans-base-artefacts/src/main/java/step/datapool/excel/ExcelFunctions.java
- step-plans/step-plans-base-artefacts/src/main/java/step/datapool/excel/WorkbookFile.java
- step-plans/step-plans-base-artefacts/src/test/java/step/datapool/excel/ExcelFunctionsTest.java
- step-plans/step-plans-base-artefacts/src/test/java/step/datapool/excel/WorkbookFileTest.java
- step-plans/step-plans-base-artefacts/src/test/java/step/datapool/excel/WorkbookSetTest.java
Sorry, IntelliJ again kept reformatting some line breaks because they're not entirely consistent in the existing source tree :-)
> SED-2118 Fix problems opening certain Excel files

- build_parameters.json
- step-node/step-node-agent/package.json
Attention: do not merge this pull request before upgrading the build server
> SED-2538 adding deploy scripts

- step-functions-plugins/step-functions-plugins-composite/step-functions-plugins-composite-def/src/main/java/step/plugins/functions/types/CompositeFunctionType.java
- step-functions-plugins/step-functions-plugins-java/step-functions-plugins-java-def/src/main/java/step/plugins/java/AbstractScriptFunctionType.java
- step-functions-plugins/step-functions-plugins-java/step-functions-plugins-java-def/src/main/java/step/plugins/java/GeneralScriptFunctionType.java
- step-functions-plugins/step-functions-plugins-jmeter/step-functions-plugins-jmeter-def/src/main/java/step/plugins/jmeter/JMeterFunctionType.java
- step-functions-plugins/step-functions-plugins-node/src/main/java/step/plugins/node/NodeFunctionType.java
- step-functions/step-functions-client-api/src/main/java/step/functions/type/AbstractFunctionType.java
- step-functions/step-functions-client/src/test/java/step/functions/execution/FunctionExecutionServiceImplTest.java
- step-functions/step-functions-client/src/test/java/step/functions/runner/TestFunctionType.java
- step-plans/step-plans-base-artefacts/src/main/java/step/engine/plugins/LocalFunctionPlugin.java
- step-plans/step-plans-base-artefacts/src/test/java/step/artefacts/handlers/CallFunctionHandlerTest.java
- step-plans/step-plans-base-artefacts/src/test/java/step/artefacts/handlers/FunctionGroupHandlerTest.java
- step-plans/step-plans-base-artefacts/src/test/java/step/artefacts/handlers/FunctionRouterTest.java
- step-plans/step-plans-base-artefacts/src/test/java/step/engine/plugins/FunctionPluginTest.java
... to have a single signature including context
> SED-2933 Consolidate AbstractFunctionType#getHandlerProperties

- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/CallFunctionHandler.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/functions/FunctionGroupSession.java
> SED-3054-keyword-adding-values-to-session-does-not-throw-an-error-anymore

- step-parent/pom.xml
> SED-1638 in-memory-collection-mongo-db-collection-different-behavior-on-empty-filters

- step-plans/step-plans-base-artefacts/src/main/java/step/repositories/LocalRepository.java
@cl-exense Please note that I've removed a part of the code that was implemented for the isolated execution mode that was removed. All the JUnit and E2E tests passed so I assume it is safe to remove it
> SED-1391 Error handling of deleted plans

- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/aggregated/AggregatedReportViewBuilder.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/aggregated/ReportNodeTimeSeries.java
Solution for requesting specific time range from aggregated tree endpoint
> SED-3564 improve-time-selector

- step-controller-plugins/step-controller-plugins-measurement/src/main/java/step/plugins/measurements/MeasurementPlugin.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/handlers/ArtefactHandler.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/aggregated/ReportNodeTimeSeries.java
@david-stephan this could also be merged to master I guess
> Sed 3634 add test cases chart

- step-plans/step-plans-core/src/main/java/step/core/artefacts/handlers/ArtefactHandler.java
> SED-3667-before-and-after-sections-using-dynamic-continue-on-error-throw-exceptions

- pom.xml
- step-plans/step-plans-base-artefacts/pom.xml
> SED-3748-vulnerability-caused-by-google-apis-for-projects-using-the-step-remote-client

- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/functions/TokenForecastingContext.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/functions/TokenForecastingExecutionPlugin.java
- step-plans/step-plans-base-artefacts/src/test/java/step/artefacts/handlers/ForHandlerTest.java
- step-plans/step-plans-core/src/main/java/step/threadpool/ThreadPool.java
- step-plans/step-plans-core/src/test/java/step/threadpool/ThreadPoolTest.java
- step-plans/step-plans-runners/src/test/java/step/localrunner/TokenForcastingTest.java
... plus some minor cleanup/refactoring
> SED-3737 Consider execution_threads_auto parameter in agent auto-provisioning

- step-plans/step-plans-base-artefacts/src/test/java/step/reporting/ResolvedPlanBuilderTest.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/ReportNodeAccessor.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/ReportNodeAccessorImpl.java
- step-plans/step-plans-core/src/main/java/step/core/artefacts/reports/aggregated/AggregatedReportViewBuilder.java
> SED-3882 aggregated-tree-should-also-display-information-about-non-ended-status

- pom.xml
> SED-3956-file-manager-file-names-containing-dir-are-considered-as-folder

- step-plans/step-plans-base-artefacts/src/test/java/step/artefacts/handlers/ForHandlerTest.java
- step-plans/step-plans-runners/src/test/java/step/localrunner/TokenForecastingTest.java
Cherry-picked the changes from master to 27.
> SED-3973 cherry-pick to 27

- step-core-model/src/main/java/step/attachments/AttachmentMeta.java
- step-core-model/src/main/java/step/attachments/SkippedAttachmentMeta.java
- step-plans/step-plans-base-artefacts/src/main/java/step/artefacts/handlers/CallFunctionHandler.java
- step-plans/step-plans-core/src/main/java/step/core/miscellaneous/ReportNodeAttachmentManager.java
…s for an execution is reached
> SED-4016 report-a-clear-warning-when-the-maximum-number-of-attachments-for-an-execution-is-reached
